services:

  # не буду пихать сюда постгрес и редис потому что на сервере они уже есть

  web:
    build: .
    container_name: django_web
    command: gunicorn --bind 0.0.0.0:8000 settings.wsgi
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    network_mode: "host"
