services:

  # не буду пихать сюда постгрес и редис потому что на сервере они уже есть

  web:
    build: .
    container_name: django_web
    command: gunicorn --bind 127.0.0.1:8001 --workers 3 --timeout 120 wsgi:application
    restart: always
    volumes:
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    network_mode: "host"
