# Generated by Django 5.0.7 on 2024-07-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('count', models.BigIntegerField(default=0, verbose_name='счетчик поиска')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to='auths.client', verbose_name='пользователь')),
            ],
        ),
    ]
