# Generated by Django 5.0.7 on 2024-07-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('-id',), 'verbose_name': 'история поиска', 'verbose_name_plural': 'история поиска'},
        ),
    ]
